# Clippy configuration for strict code quality enforcement
# Following CLAUDE.md guidelines

# Lint groups to deny (treat as errors)
disallowed-macros = [
  "std::unimplemented!",
  "std::unreachable!",
  "std::panic!",
  "std::todo!",
]

# Specific lints to enforce
avoid-breaking-exported-api = false
msrv = "1.70"

# Performance and safety
too-many-arguments-threshold = 7
type-complexity-threshold = 250
trivial-copy-size-limit = 128
single-char-binding-names-threshold = 5