# Rustfmt configuration for consistent formatting
# Following CLAUDE.md guidelines - using only stable options

# Basic formatting
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Function and struct formatting
fn_params_layout = "Tall"
reorder_imports = true
use_field_init_shorthand = false
use_try_shorthand = false
force_explicit_abi = true

# Newlines and spacing
newline_style = "Unix"
remove_nested_parens = true
chain_width = 60
single_line_if_else_max_width = 50
array_width = 60
attr_fn_like_width = 70
struct_lit_width = 18
struct_variant_width = 35
short_array_element_width_threshold = 10