# Rustfmt configuration for consistent formatting
# Following CLAUDE.md guidelines

# Basic formatting
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Function and struct formatting
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
trailing_comma = "Vertical"
trailing_semicolon = true
match_block_trailing_comma = false

# Import formatting
imports_layout = "Mixed"
imports_granularity = "Crate"
reorder_imports = true
group_imports = "StdExternalCrate"

# String formatting
format_strings = false
format_macro_matchers = true
format_macro_bodies = true

# Code organization
reorder_impl_items = true
type_punctuation_density = "Wide"
use_field_init_shorthand = false
use_try_shorthand = false
force_explicit_abi = true

# Documentation
format_code_in_doc_comments = true
normalize_doc_attributes = true
doc_comment_code_block_width = 80

# Error handling
error_on_line_overflow = false
error_on_unformatted = false

# Newlines and spacing
newline_style = "Unix"
remove_nested_parens = true
spaces_around_ranges = false
binop_separator = "Front"
chain_width = 60
single_line_if_else_max_width = 50
where_single_line = false
force_multiline_blocks = false
struct_field_align_threshold = 0
array_width = 60
attr_fn_like_width = 70
struct_lit_width = 18
struct_variant_width = 35
enum_discrim_align_threshold = 0
match_arm_blocks = true
force_multiline_blocks = false
fn_single_line = false
where_single_line = false
empty_item_single_line = true
struct_lit_single_line = true
fn_params_layout = "Tall"
overflow_delimited_expr = false
combine_control_expr = true
short_array_element_width_threshold = 10