name: Debug Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ '.github/workflows/debug.yml' ]

jobs:
  debug:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@1.65.0

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install npm dependencies
        run: npm ci

      - name: Check Rust compilation
        run: cargo check --manifest-path src-tauri/Cargo.toml

      - name: Check Tauri CLI
        run: |
          npm run tauri --version || echo "Tauri CLI not found"
          npx tauri --version || echo "npx tauri not found"

      - name: Install Tauri CLI globally
        run: npm install -g @tauri-apps/cli

      - name: Check Tauri CLI again
        run: tauri --version

      - name: Try simple Tauri build
        run: |
          echo "Attempting Tauri build..."
          npm run build 2>&1 | tee build.log || true
          echo "Build completed with exit code: $?"
          echo "Last 20 lines of output:"
          tail -20 build.log || echo "No log file found"